subindo a migration
chagasbarros/Orion-Bootcamp-Projeto-Civitas-Back pull request #1
Opened 2024-10-08 20:10 UTC by chagasbarros

eu fiz a migration e as entidades Role e User

2024-10-09 15:20 UTC, robsonfgomes-newrizon requested changes

2024-10-09 15:20 UTC, robsonfgomes-newrizon commented on migration/1728390448734-modelDataBase.ts
Não há necessidade de migrations pra criação de tabelas, uma vez que a sincronização com o banco de dados está ativa:
synchronize: true

2024-10-09 15:20 UTC, robsonfgomes-newrizon commented on package-lock.json
Esse arquivo não deve estar no versionamento, ele é gerado de forma automática a partir do package.json ao instalar as dependências do projeto.

2024-10-09 15:20 UTC, robsonfgomes-newrizon commented on package.json
É bom fixar as dependência do projeto para não correr risco de quebra devido a atualização das dependências.
Pra fixar basta remover o  ^

2024-10-09 15:20 UTC, robsonfgomes-newrizon commented on src/entity/Role.ts
> +  @ManyToMany(() => User)
Aqui é interessante definir o nome da tabela de relacionamento, percebi que o typeOrm criou uma tabela denominada roles_users_users, quando o correto seria roles_users.
`  @ManyToMany(() => User)
  @JoinTable({ name: 'roles_users' })
  users: User[];`

2024-10-09 15:20 UTC, robsonfgomes-newrizon commented on src/entity/Role.ts
> +  createdAt: string;
O tipo correto é o Date;

2024-10-09 15:20 UTC, robsonfgomes-newrizon commented on src/entity/Role.ts
Também é possível adicionar métodos para definir as datas de criação e atualização de forma automática.

// Methods
  @BeforeInsert()
  public setCreateAt(): void {
    this.createdAt = new Date();
  }

  @BeforeInsert()
  @BeforeUpdate()
  public setUpdateAt(): void {
    this.updatedAt = new Date();
  }

2024-10-09 15:20 UTC, robsonfgomes-newrizon commented on src/entity/User.ts
> +  createdAt: string;
Mesma coisa, definir o tipo Date

2024-10-09 15:20 UTC, robsonfgomes-newrizon commented on src/entity/User.ts
> +}
Faltou adicionar o relacionamento para a entidade de roles:

```
// Relationships
  @ManyToMany(() => Role, (role) => role.users)
  roles: Role[];

  // Methods
  @BeforeInsert()
  public setCreateAt(): void {
    this.createdAt = new Date();
  }

  @BeforeInsert()
  @BeforeUpdate()
  public setUpdateAt(): void {
    this.updatedAt = new Date();
  }
```

2024-10-09 17:53 UTC, robsonfgomes-newrizon commented on src/entity/Role.ts
> +  name: string;
Aqui seria interessante criar um ENUM para definir os nomes das permissões de acesso.
Por exemplo:
export enum EnumRoles {
   ADMIN = 'ADMIN',
   TEACHER = 'TEACHER',
   TUTOR = 'TUTOR'
}

2024-10-10 09:23 UTC, chagasbarros reviewed
Crie o ENUM para definir os nomes de acesso.

2024-10-10 09:23 UTC, chagasbarros commented on src/entity/User.ts
> +}
Criei o relacionamento no arquivo User.ts.

2024-10-10 09:23 UTC, chagasbarros commented on src/entity/Role.ts
> +  @ManyToMany(() => User)
Defini o nome da tabela de relacionamento: 'roles_users'.

2024-10-10 09:23 UTC, chagasbarros commented on src/entity/Role.ts
Adicionei os métodos @BeforeInsert e o @BeforeUpdate as colunas (createdAt e updateAT) nos dois arquivos Role.ts e User.ts.

2024-10-10 09:23 UTC, chagasbarros commented on package.json
Fixei as dependências do projeto com a remoção do ^.

2024-10-10 09:23 UTC, chagasbarros commented on migration/1728390448734-modelDataBase.ts
removi a pasta migration.

2024-10-10 09:26 UTC, chagasbarros commented on package-lock.json
Adicionei o arquivo package-lock.json ao .gitignore.

2024-10-10 09:27 UTC, chagasbarros commented on src/entity/Role.ts
> +  createdAt: string;
Adicionei o tipo Date.

2024-10-10 09:27 UTC, chagasbarros commented on src/entity/User.ts
> +  createdAt: string;
Adicionei o tipo Date.

2024-10-10 09:27 UTC, chagasbarros commented on src/entity/Role.ts
> +  name: string;
Crie o ENUM para definir os nomes de acesso.

2024-10-10 13:03 UTC, merged