criei os repositories
chagasbarros/Orion-Bootcamp-Projeto-Civitas-Back pull request #2
Opened 2024-10-10 20:55 UTC by chagasbarros

Criei os repositories para os entidades User.ts e Role.ts, 
Organizei o código das entidades por colunas, relacionamentos e métodos.
Criei o caminho: '/model/enums/roleEnum.ts.

2024-10-11 11:31 UTC, robsonfgomes-newrizon requested changes

2024-10-11 11:31 UTC, robsonfgomes-newrizon commented on src/models/enums/roleEnum.ts
Por padrão, seria bom começar alterar o nome do arquivo para 'EnumRoles'

2024-10-11 11:31 UTC, robsonfgomes-newrizon commented on src/models/enums/roleEnum.ts
> +  TUTOR = 'TUTOR'
Esse TUTOR adicionei apenas como exempo, seria bom verificar se outra nomenclatura atenderia melhor (ou não).

2024-10-11 11:31 UTC, robsonfgomes-newrizon commented on src/repositories/UserRepository.ts
> +  async findUserByEmail(email: string): Promise<User | undefined> {
Adicionei esse método apenas como exemplo, mas se for manter precisa documentar. Todos os métodos precisam estar documentados no código.
No exemplo que mandei no discord um exemplo de documentação do método.

2024-10-11 11:31 UTC, robsonfgomes-newrizon commented on src/entity/Role.ts
> +    default: enumRoles.TUTOR
Nesse caso, faz sentido deixar uma role de acesso padrão?
Creio que o ideal seja o usuário obrigatoriamente definir a role.

2024-10-11 16:53 UTC, chagasbarros commented on src/models/enums/roleEnum.ts
> +  TUTOR = 'TUTOR'
Eu coloquei Guardian, guardião em inglês. Conceito: O guardião é o responsável legal de uma criança, mas os pais continuam a ter autoridade sobre ela.

2024-10-11 16:54 UTC, chagasbarros commented on src/repositories/UserRepository.ts
> +  async findUserByEmail(email: string): Promise<User | undefined> {
Eu fiz a documentação, eu acho que vai ser útil. Também serve como exemplo para a documentação.

2024-10-11 16:55 UTC, chagasbarros commented on src/entity/Role.ts
> +    default: enumRoles.TUTOR
Concordo com você, tem que ser obrigatório o usuário definir a role, então exclui o default.

2024-10-13 01:21 UTC, robsonfgomes-newrizon approved these changes

2024-10-13 01:22 UTC, merged