Feature/auth jwt
chagasbarros/Orion-Bootcamp-Projeto-Civitas-Back pull request #3
Opened 2024-10-11 06:46 UTC by Muril0S4lvador

Feito a lógica de autenticação, faltando apenas as repositories para integrar com o banco de dados

2024-10-11 11:57 UTC, robsonfgomes-newrizon requested changes

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on docker-compose.yml
> +      JWT_SECRET: 'Rizon-bootCamp'
Esse dado não pode estar presente no versionamento, é um dado sensível e traz vulnerabilidades para a aplicação.
Deve ser colocado em um arquivo .env por exemplo.

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on package-lock.json
Esse arquivo deve ser removido do versionamento.

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/controller/LoginController.ts
> +        expiresIn: '4h'
Aumentar pra 24h

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/controller/LoginController.ts
> +    const existingUser = users.find((user) => user.username === username);
Resolver o TODO

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/controller/LoginController.ts
> +      return new BadRequestError(response, 'Dados Incorretos');
Talvez seja interessante padronizar a mensagem para: "Nome de usuário ou senha incorretos"

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/controller/LoginController.ts
> +      return new NotFoundError(response, 'Usuário não encontrado');
Talvez seja interessante padronizar a mensagem para: "Nome de usuário ou senha incorretos"

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/controller/LoginController.ts
> +    const token = jwt.sign(
Não deveria guardar esse token no banco de dados?
Como você vai validar se o token recebido posteriormente existe e é um token válido? Ou como vai saber que esse token gerado está vinculado ao usuário que o enviou?

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/controller/LoginController.ts
> +    return new ok(response, token);
Os métodos dessa classe de retorno podem ser métodos estáticos, não é necessário instanciar uma classe apenas pra obter o retorno da API.
Também seria interessante melhorar a nomenclatura desses métodos. Vou indicar lá na classe.

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/helpers/apiReturns.ts
Talvez renomear a classe para "RouteResponse", fica mais claro e intuitivo.

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/helpers/apiReturns.ts
> +export class ok {
Criar métodos estáticos dentro da classe RouteResponse

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/helpers/apiReturns.ts
> +export class ok {
alterar para success, na hora de chamar ficaria RouteResponse.success, muito mais intuitivo e conciso. Não acha?

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/helpers/apiReturns.ts
> +export class NotFoundError extends ApiReturn {
Só notFound já está bom.

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/helpers/apiReturns.ts
> +  public readonly statusCode: number = 200;
Suguiro os seguintes métodos:
success - 200
successCreate - 201
successEmpty - 204
error - 400
serverError - 500
notFound - 404
unauthorizedError - 401

Todos serão métodos estáticos dentro da classe RouteResponse.
[](https://www.httpstatus.com.br/)

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/routes.ts
> +router.post('/login', new LoginController().login);
Seria bom adicionar um comentário acima do grupo de rotas. Por exemplo:
`// Auth`

2024-10-11 11:57 UTC, robsonfgomes-newrizon commented on src/controller/LoginController.ts
Acho melhor mudar o nome do controller para "AuthController", afinal, aqui terão vários endpoints, não só o login.

2024-10-14 04:12 UTC, Muril0S4lvador commented
Feita as alterações pedidas e adicionados interações com o banco de dados

2024-10-14 16:16 UTC, Muril0S4lvador commented on docker-compose.yml
> +      JWT_SECRET: 'Rizon-bootCamp'
> Esse dado não pode estar presente no versionamento, é um dado sensível e traz vulnerabilidades para a aplicação. Deve ser colocado em um arquivo .env por exemplo.

feito

2024-10-14 16:51 UTC, Muril0S4lvador reviewed
feito as correções

2024-10-14 16:53 UTC, Muril0S4lvador commented on package-lock.json
feito

2024-10-14 16:53 UTC, Muril0S4lvador commented on src/controller/LoginController.ts
> +        expiresIn: '4h'
feito

2024-10-14 16:53 UTC, Muril0S4lvador commented on src/controller/LoginController.ts
> +      return new BadRequestError(response, 'Dados Incorretos');
feito

2024-10-14 16:53 UTC, Muril0S4lvador commented on src/controller/LoginController.ts
> +      return new NotFoundError(response, 'Usuário não encontrado');
feito

2024-10-14 16:54 UTC, Muril0S4lvador commented on src/controller/LoginController.ts
> +    const token = jwt.sign(
feito

2024-10-14 16:54 UTC, Muril0S4lvador commented on src/controller/LoginController.ts
> +    return new ok(response, token);
feito

2024-10-14 16:54 UTC, Muril0S4lvador commented on src/helpers/apiReturns.ts
feito

2024-10-14 16:54 UTC, Muril0S4lvador commented on src/helpers/apiReturns.ts
> +export class ok {
feito

2024-10-14 16:54 UTC, Muril0S4lvador commented on src/helpers/apiReturns.ts
> +export class NotFoundError extends ApiReturn {
feito

2024-10-14 16:54 UTC, Muril0S4lvador commented on src/helpers/apiReturns.ts
> +  public readonly statusCode: number = 200;
feito

2024-10-14 16:54 UTC, Muril0S4lvador commented on src/routes.ts
> +router.post('/login', new LoginController().login);
feito

2024-10-14 16:54 UTC, Muril0S4lvador commented on src/controller/LoginController.ts
feito

2024-10-15 15:40 UTC, robsonfgomes-newrizon requested changes

2024-10-16 06:31 UTC, Muril0S4lvador commented on src/helpers/RouteResponse.ts
> +  public static sucessCreated(res: Response, content, message?: string) {
Obrigado!! Feita a documentação.

2024-10-17 13:32 UTC, robsonfgomes-newrizon commented
É importante testar via swagger pra garantir que a funcionalidade está operante.
![image](https://github.com/user-attachments/assets/8ef63d79-c90a-4b72-8779-5205a5123b39)

2024-10-17 13:32 UTC, robsonfgomes-newrizon requested changes
Corrigir o endpoint de autenticação.

2024-10-18 03:11 UTC, Muril0S4lvador commented
> Corrigir o endpoint de autenticação.

feito

2024-10-18 12:56 UTC, robsonfgomes-newrizon approved these changes

2024-10-18 12:57 UTC, merged